### ISSUE TITLE
cannot import name 'CRS' from 'pyproj'

### ISSUE THREAD

**Issue by hin20001024** [EY-Data-Science-Program/2021-Better-Working-World-Data-Challenge#54]
I failed to import name 'CRS' from 'pyproj'. And I google-searched about it.

[]( https://stackoverflow.com/questions/59658167/cannot-import-name-crs-from-pyproj-for-using-the-osmnx-library/62958055 )

There are some suggested solutions, but it doesn't work for me because I am using Anaconda Jupyter Notebook to do modeling.

![螢幕擷取畫面 2021-05-04 044913](https://user-images.githubusercontent.com/70860455/117089123-30738780-ad87-11eb-97ec-37fa8a94f1f7.jpg)

**Comment by alexgleith** [comment]
Building Python environments is tricky. What has happened here is that your version of pyproj is different to the one we are expecting you to have.

Looking here, Datacube should work with pyproj >= 2.5: https://github.com/opendatacube/datacube-core/blob/develop/setup.py#L92

What is the output of `pip freeze`?

It may be that your version is too recent, or too old!

**Comment by hin20001024** [comment]
> Building Python environments is tricky. What has happened here is that your version of pyproj is different to the one we are expecting you to have.
> 
> Looking here, Datacube should work with pyproj >= 2.5: https://github.com/opendatacube/datacube-core/blob/develop/setup.py#L92
> 
> What is the output of `pip freeze`?
> 
> It may be that your version is too recent, or too old!

Pyproj is a very old version... []https://pyproj4.github.io/pyproj/stable/installation.html

btw, I want to know whether importing data from datacube is necessary? because I realize that some training data and test data are provided, such as []https://datascience.ey.com/challenge/5

**Dataset files**
challenge1_train.csv
sample_submission.csv
challenge1_test.csv
Challenge_Terms_and_conditions.pdf
